"""
Incident Service — business logic layer.

This is the only place business rules and decisions live.
No SQL queries here — all DB access goes through IncidentRepository.
No HTTP concerns here — all HTTP handling stays in the API layer.

Flow: API -> Service -> Repository -> Database
"""
import logging
from sqlalchemy.ext.asyncio import AsyncSession
from app.modules.incidents.repository import IncidentRepository
from app.modules.incidents.schemas import (
    IncidentCreate, IncidentUpdate, IncidentResponse, IncidentListResponse
)
from app.common.exceptions.base import NotFoundError, BadRequestError

logger = logging.getLogger(__name__)


class IncidentService:
    """
    Business logic layer for incidents.
    Validates inputs, calls repository, handles exceptions,
    and prepares response objects.
    """

    def __init__(self, db: AsyncSession):
        # Repository is injected via the db session
        self.repo = IncidentRepository(db)

    async def create_incident(self, payload: IncidentCreate) -> IncidentResponse:
        """
        Create a new incident.
        Incident number is auto-generated by the repository.
        """
        logger.info(f"Creating incident: {payload.short_description}")
        incident = await self.repo.create(payload.model_dump())
        logger.info(f"Incident created: {incident.incident_number}")
        return IncidentResponse.model_validate(incident)

    async def get_incident(self, incident_id: str) -> IncidentResponse:
        """
        Fetch a single incident by ID or incident number (INC0000001).
        Raises NotFoundError if the incident does not exist.
        """
        # Detect if input is an incident number (INCxxxxxxx) or UUID
        if incident_id.upper().startswith("INC"):
            incident = await self.repo.get_by_number(incident_id.upper())
        else:
            incident = await self.repo.get_by_id(incident_id)

        if not incident:
            logger.warning(f"Incident not found: {incident_id}")
            raise NotFoundError(f"Incident '{incident_id}' not found")
        return IncidentResponse.model_validate(incident)

    async def list_incidents(
        self,
        page: int = 1,
        page_size: int = 20,
        priority: str | None = None,
        state: str | None = None,
        category: str | None = None,
        assignment_group: str | None = None,
        sort_by: str = "created_at",
        sort_order: str = "desc",
    ) -> IncidentListResponse:
        """
        Return a paginated list of incidents.
        Supports filtering by priority, state, category, assignment_group.
        Supports sorting by any column in asc/desc order.
        """
        # Convert page number to SQL offset
        offset = (page - 1) * page_size

        incidents, total = await self.repo.get_all(
            offset=offset,
            limit=page_size,
            priority=priority,
            state=state,
            category=category,
            assignment_group=assignment_group,
            sort_by=sort_by,
            sort_order=sort_order,
        )

        # Ceiling division for total pages
        pages = -(-total // page_size)

        return IncidentListResponse(
            items=[IncidentResponse.model_validate(i) for i in incidents],
            total=total,
            page=page,
            page_size=page_size,
            pages=pages,
        )

    async def update_incident(self, incident_id: str, payload: IncidentUpdate) -> IncidentResponse:
        """
        Update an existing incident.
        Only fields explicitly provided in the payload are updated.
        Returns the existing record unchanged if no fields provided.
        Raises NotFoundError if the incident does not exist.
        """
        if incident_id.upper().startswith("INC"):
            existing = await self.repo.get_by_number(incident_id.upper())
        else:
            existing = await self.repo.get_by_id(incident_id)

        if not existing:
            logger.warning(f"Update failed — incident not found: {incident_id}")
            raise NotFoundError(f"Incident '{incident_id}' not found")

        # exclude_unset=True ensures only fields explicitly set in the payload are updated,
        # but preserves None values (unlike exclude_none which silently drops them)
        update_data = payload.model_dump(exclude_unset=True)
        if not update_data:
            # Nothing to update — return as is
            logger.warning(f"Update called with no fields: {incident_id}")
            return IncidentResponse.model_validate(existing)

        incident = await self.repo.update(existing.id, update_data)
        logger.info(f"Incident updated: {incident.incident_number}")
        return IncidentResponse.model_validate(incident)

    async def delete_incident(self, incident_id: str) -> None:
        """
        Delete an incident permanently.
        Raises NotFoundError if the incident does not exist.
        """
        existing = await self.repo.get_by_id(incident_id)
        if not existing:
            logger.warning(f"Delete failed — incident not found: {incident_id}")
            raise NotFoundError(f"Incident '{incident_id}' not found")

        await self.repo.delete(incident_id)
        logger.info(f"Incident deleted: {existing.incident_number}")

    async def search_incidents(
        self,
        query: str,
        page: int = 1,
        page_size: int = 20,
        priority: str | None = None,
        state: str | None = None,
        category: str | None = None,
        assignment_group: str | None = None,
    ) -> IncidentListResponse:
        """
        Search incidents by keyword with optional filters.
        Searches across: incident_number, short_description,
        description, caller, assigned_to.
        Minimum query length is 2 characters.
        """
        if not query or len(query.strip()) < 2:
            raise BadRequestError("Search query must be at least 2 characters")

        offset = (page - 1) * page_size
        incidents, total = await self.repo.search(
            query=query.strip(),
            offset=offset,
            limit=page_size,
            priority=priority,
            state=state,
            category=category,
            assignment_group=assignment_group,
        )

        # Handle case where search returns 0 results
        pages = -(-total // page_size) if total else 0

        return IncidentListResponse(
            items=[IncidentResponse.model_validate(i) for i in incidents],
            total=total,
            page=page,
            page_size=page_size,
            pages=pages,
        )
