"""create_shift_roster_table

Revision ID: 15fef2bf1df7
Revises: 78b5282e58c6
Create Date: 2026-08-06 13:17:54.298926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fef2bf1df7'
down_revision = '78b5282e58c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_roster',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_group', sa.String(length=200), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('shift', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('roster_month', sa.String(length=7), nullable=False),
    sa.Column('day_1', sa.String(length=20), nullable=True),
    sa.Column('day_2', sa.String(length=20), nullable=True),
    sa.Column('day_3', sa.String(length=20), nullable=True),
    sa.Column('day_4', sa.String(length=20), nullable=True),
    sa.Column('day_5', sa.String(length=20), nullable=True),
    sa.Column('day_6', sa.String(length=20), nullable=True),
    sa.Column('day_7', sa.String(length=20), nullable=True),
    sa.Column('day_8', sa.String(length=20), nullable=True),
    sa.Column('day_9', sa.String(length=20), nullable=True),
    sa.Column('day_10', sa.String(length=20), nullable=True),
    sa.Column('day_11', sa.String(length=20), nullable=True),
    sa.Column('day_12', sa.String(length=20), nullable=True),
    sa.Column('day_13', sa.String(length=20), nullable=True),
    sa.Column('day_14', sa.String(length=20), nullable=True),
    sa.Column('day_15', sa.String(length=20), nullable=True),
    sa.Column('day_16', sa.String(length=20), nullable=True),
    sa.Column('day_17', sa.String(length=20), nullable=True),
    sa.Column('day_18', sa.String(length=20), nullable=True),
    sa.Column('day_19', sa.String(length=20), nullable=True),
    sa.Column('day_20', sa.String(length=20), nullable=True),
    sa.Column('day_21', sa.String(length=20), nullable=True),
    sa.Column('day_22', sa.String(length=20), nullable=True),
    sa.Column('day_23', sa.String(length=20), nullable=True),
    sa.Column('day_24', sa.String(length=20), nullable=True),
    sa.Column('day_25', sa.String(length=20), nullable=True),
    sa.Column('day_26', sa.String(length=20), nullable=True),
    sa.Column('day_27', sa.String(length=20), nullable=True),
    sa.Column('day_28', sa.String(length=20), nullable=True),
    sa.Column('day_29', sa.String(length=20), nullable=True),
    sa.Column('day_30', sa.String(length=20), nullable=True),
    sa.Column('day_31', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_roster_assigned_to'), 'shift_roster', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_shift_roster_assignment_group'), 'shift_roster', ['assignment_group'], unique=False)
    op.create_index(op.f('ix_shift_roster_roster_month'), 'shift_roster', ['roster_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_roster_roster_month'), table_name='shift_roster')
    op.drop_index(op.f('ix_shift_roster_assignment_group'), table_name='shift_roster')
    op.drop_index(op.f('ix_shift_roster_assigned_to'), table_name='shift_roster')
    op.drop_table('shift_roster')
    # ### end Alembic commands ###
