"""fix_enum_values_lowercase

Revision ID: 2dab1e1fa831
Revises: e67628208ea8
Create Date: 2026-08-11 15:41:30.215569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dab1e1fa831'
down_revision = 'e67628208ea8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
