"""shift_roster_string_columns

Revision ID: 76deb7e985b5
Revises: 2dab1e1fa831
Create Date: 2026-08-11 16:20:06.208683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76deb7e985b5'
down_revision = '2dab1e1fa831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engineers', 'level',
               existing_type=postgresql.ENUM('L1', 'L2', 'L3', name='engineerlevel'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('engineers', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', name='engineerstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('shift_roster', 'shift_code',
               existing_type=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('shift_roster_history', 'previous_shift',
               existing_type=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('shift_roster_history', 'new_shift',
               existing_type=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('shift_roster_uploads', 'upload_status',
               existing_type=postgresql.ENUM('SUCCESS', 'PARTIAL', 'FAILED', name='uploadstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_roster_uploads', 'upload_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SUCCESS', 'PARTIAL', 'FAILED', name='uploadstatus'),
               existing_nullable=False)
    op.alter_column('shift_roster_history', 'new_shift',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               existing_nullable=False)
    op.alter_column('shift_roster_history', 'previous_shift',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               existing_nullable=False)
    op.alter_column('shift_roster', 'shift_code',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'),
               existing_nullable=False)
    op.alter_column('engineers', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', name='engineerstatus'),
               existing_nullable=False)
    op.alter_column('engineers', 'level',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('L1', 'L2', 'L3', name='engineerlevel'),
               existing_nullable=True)
    # ### end Alembic commands ###
