"""create_incidents_table

Revision ID: 78b5282e58c6
Revises: 
Create Date: 2026-07-30 02:31:07.738437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b5282e58c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_number', sa.String(length=20), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incidentpriority'), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'CANCELLED', name='incidentstate'), nullable=False),
    sa.Column('category', sa.Enum('NETWORK', 'HARDWARE', 'SOFTWARE', 'DATABASE', 'SECURITY', 'ACCESS', 'EMAIL', 'VPN', 'APPLICATION', 'OTHER', name='incidentcategory'), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('impact', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='incidentimpact'), nullable=False),
    sa.Column('urgency', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='incidenturgency'), nullable=False),
    sa.Column('assignment_group', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('caller', sa.String(length=100), nullable=True),
    sa.Column('configuration_item', sa.String(length=100), nullable=True),
    sa.Column('business_service', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', 'DR', name='incidentenvironment'), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'MONITORING', 'EMAIL', 'PHONE', 'SELF_SERVICE', 'API', name='incidentsource'), nullable=False),
    sa.Column('work_notes', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_number'), 'incidents', ['incident_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_incident_number'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
