"""normalized_shift_roster_schema

Revision ID: 9092bd4e4a4f
Revises: 15fef2bf1df7
Create Date: 2026-08-06 14:57:23.609516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9092bd4e4a4f'
down_revision = '15fef2bf1df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_group', sa.String(length=200), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('default_shift', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='engineerlevel'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='engineerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineers_assigned_to'), 'engineers', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_engineers_assignment_group'), 'engineers', ['assignment_group'], unique=False)
    op.create_index(op.f('ix_engineers_email'), 'engineers', ['email'], unique=True)
    op.create_index(op.f('ix_engineers_level'), 'engineers', ['level'], unique=False)
    op.create_index(op.f('ix_engineers_status'), 'engineers', ['status'], unique=False)
    op.create_table('shift_roster_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('roster_start_date', sa.Date(), nullable=False),
    sa.Column('roster_end_date', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('imported_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('upload_status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='uploadstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_roster',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('engineer_id', sa.String(length=36), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sa.Enum('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['shift_roster_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_roster_engineer_id'), 'shift_roster', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_shift_roster_roster_date'), 'shift_roster', ['roster_date'], unique=False)
    op.create_index(op.f('ix_shift_roster_shift_code'), 'shift_roster', ['shift_code'], unique=False)
    op.create_index(op.f('ix_shift_roster_upload_id'), 'shift_roster', ['upload_id'], unique=False)
    op.create_table('shift_roster_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roster_id', sa.String(length=36), nullable=False),
    sa.Column('engineer_id', sa.String(length=36), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('previous_shift', sa.Enum('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'), nullable=False),
    sa.Column('new_shift', sa.Enum('SHIFT1', 'SHIFT2', 'SHIFT3', 'WEEK_OFF', 'PLANNED_LEAVE', 'RESTRICTED_HOLIDAY', name='shiftcode'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['shift_roster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_roster_history_engineer_id'), 'shift_roster_history', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_shift_roster_history_roster_id'), 'shift_roster_history', ['roster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_roster_history_roster_id'), table_name='shift_roster_history')
    op.drop_index(op.f('ix_shift_roster_history_engineer_id'), table_name='shift_roster_history')
    op.drop_table('shift_roster_history')
    op.drop_index(op.f('ix_shift_roster_upload_id'), table_name='shift_roster')
    op.drop_index(op.f('ix_shift_roster_shift_code'), table_name='shift_roster')
    op.drop_index(op.f('ix_shift_roster_roster_date'), table_name='shift_roster')
    op.drop_index(op.f('ix_shift_roster_engineer_id'), table_name='shift_roster')
    op.drop_table('shift_roster')
    op.drop_table('shift_roster_uploads')
    op.drop_index(op.f('ix_engineers_status'), table_name='engineers')
    op.drop_index(op.f('ix_engineers_level'), table_name='engineers')
    op.drop_index(op.f('ix_engineers_email'), table_name='engineers')
    op.drop_index(op.f('ix_engineers_assignment_group'), table_name='engineers')
    op.drop_index(op.f('ix_engineers_assigned_to'), table_name='engineers')
    op.drop_table('engineers')
    # ### end Alembic commands ###
