"""add_assignment_rr_state_and_history

Revision ID: e67628208ea8
Revises: 9092bd4e4a4f
Create Date: 2026-08-11 02:36:54.094112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67628208ea8'
down_revision = '9092bd4e4a4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_group_rr_state',
    sa.Column('assignment_group', sa.String(length=200), nullable=False),
    sa.Column('last_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('assignment_group')
    )
    op.create_table('assignment_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('incident_number', sa.String(length=20), nullable=False),
    sa.Column('assignment_group', sa.String(length=200), nullable=False),
    sa.Column('engineer_id', sa.String(length=36), nullable=False),
    sa.Column('engineer_name', sa.String(length=100), nullable=False),
    sa.Column('engineer_email', sa.String(length=150), nullable=False),
    sa.Column('shift_code', sa.String(length=20), nullable=True),
    sa.Column('roster_date', sa.String(length=10), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llm_resolved_group', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_history_assignment_group'), 'assignment_history', ['assignment_group'], unique=False)
    op.create_index(op.f('ix_assignment_history_engineer_id'), 'assignment_history', ['engineer_id'], unique=False)
    op.create_index(op.f('ix_assignment_history_incident_id'), 'assignment_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_history_incident_id'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_engineer_id'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_assignment_group'), table_name='assignment_history')
    op.drop_table('assignment_history')
    op.drop_table('assignment_group_rr_state')
    # ### end Alembic commands ###
